displayName=Iron Path
author=Connor Fitzgerald
description=Sync characters, skills, goals, loot, and Collection Log progress with Iron Path
tags=ironman,goals,quests,skills,loot,grinds,banked,xp,collection,log,tracker
plugins=gg.ironpath.IronPathPlugin
version=0.4.0
build=standard
