package gg.ironpath;

import net.runelite.client.config.Config;
import net.runelite.client.config.ConfigGroup;
import net.runelite.client.config.ConfigItem;
import net.runelite.client.config.ConfigSection;

@ConfigGroup(IronPathConfig.GROUP)
public interface IronPathConfig extends Config
{
    String GROUP = "ironpath";
    String DEFAULT_API_ORIGIN = "https://www.ironpathosrs.com";

    @ConfigSection(
        name = "Connection",
        description = "Link this RuneLite profile to Iron Path",
        position = 0,
        closedByDefault = true
    )
    String connectionSection = "connection";

    @ConfigSection(
        name = "Sync",
        description = "Choose when Iron Path synchronizes account data",
        position = 1,
        closedByDefault = true
    )
    String syncSection = "sync";

    @ConfigSection(
        name = "Sidebar display",
        description = "Choose which sections appear in the Iron Path sidebar",
        position = 2,
        closedByDefault = true
    )
    String sidebarSection = "sidebar";

    @ConfigItem(
        keyName = "apiOrigin",
        name = "API origin",
        description = "HTTPS web application origin that receives synchronized Iron Path data; changing it requires relinking",
        position = 0,
        section = connectionSection
    )
    default String apiOrigin()
    {
        return DEFAULT_API_ORIGIN;
    }

    @ConfigItem(
        keyName = "linkingCode",
        name = "Linking code",
        description = "Single-use code generated by the Iron Path website",
        warning = "Linking sends your RuneScape name, account mode, levels and XP, quests, bank, inventory, "
            + "equipment, loot, kill counts, Collection Log, and goal progress to the configured Iron Path API origin.",
        position = 1,
        section = connectionSection
    )
    default String linkingCode()
    {
        return "";
    }

    @ConfigItem(
        keyName = "autoSync",
        name = "Automatic sync",
        description = "Refresh goals every 15 seconds, sync progress every two minutes, and sync bank changes shortly after they occur",
        warning = "This feature submits your IP address to a 3rd-party server not controlled or verified by RuneLite developers",
        position = 0,
        section = syncSection
    )
    default boolean autoSync()
    {
        return false;
    }

    @ConfigItem(
        keyName = "showConnection",
        name = "Show connection",
        description = "Show character linking status and the Relink button in the sidebar",
        position = 0,
        section = sidebarSection
    )
    default boolean showConnection()
    {
        return true;
    }

    @ConfigItem(
        keyName = "showSyncActivity",
        name = "Show sync activity",
        description = "Show session kills, pending uploads, last sync time, and manual sync controls",
        position = 1,
        section = sidebarSection
    )
    default boolean showSyncActivity()
    {
        return true;
    }

    @ConfigItem(
        keyName = "showCollectionLog",
        name = "Show Collection Log",
        description = "Show Collection Log detection, last-sync status, and its sync control",
        position = 2,
        section = sidebarSection
    )
    default boolean showCollectionLog()
    {
        return true;
    }

    @ConfigItem(
        keyName = "showRecentCollections",
        name = "Show recent collections",
        description = "Show recently captured Collection Log items",
        position = 3,
        section = sidebarSection
    )
    default boolean showRecentCollections()
    {
        return true;
    }

    @ConfigItem(
        keyName = "showRecentKills",
        name = "Show recent kills",
        description = "Show recent tracked NPC kills",
        position = 4,
        section = sidebarSection
    )
    default boolean showRecentKills()
    {
        return true;
    }

    @ConfigItem(
        keyName = "showGoals",
        name = "Show goals",
        description = "Show active and completed Iron Path goals",
        position = 5,
        section = sidebarSection
    )
    default boolean showGoals()
    {
        return true;
    }
}
