package gg.ironpath;

import net.runelite.client.config.Config;
import net.runelite.client.config.ConfigGroup;
import net.runelite.client.config.ConfigItem;

@ConfigGroup(IronPathConfig.GROUP)
public interface IronPathConfig extends Config
{
    String GROUP = "ironpath";

    @ConfigItem(
        keyName = "apiOrigin",
        name = "API origin",
        description = "Iron Path web application origin",
        position = 0
    )
    default String apiOrigin()
    {
        return "https://ironpath.gg";
    }

    @ConfigItem(
        keyName = "linkingCode",
        name = "Linking code",
        description = "Single-use code generated by the Iron Path website",
        position = 1
    )
    default String linkingCode()
    {
        return "";
    }

    @ConfigItem(
        keyName = "autoSync",
        name = "Automatic sync",
        description = "Refresh goals every 15 seconds, sync progress every two minutes, and sync bank changes shortly after they occur",
        position = 2
    )
    default boolean autoSync()
    {
        return true;
    }
}
